<a href="https://colab.research.google.com/github/oytungunes/PythonCodeExamples/blob/main/NestedKfold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.model_selection import KFold, StratifiedKFold

import numpy as np
numoffold=5

X = np.array([[1], [2], [3], [4],[5],[6],[7],[8],[9],[10]])
Y = np.array([0, 0, 0, 0, 0, 1,1,1,1, 1])


skf = StratifiedKFold(n_splits=numoffold,shuffle=True, random_state = None)
skf.get_n_splits(X, Y)




dim1,dim2 = X.shape
valsize=valsize=round(dim1/numoffold)

foldnumber=0

for all_index, test_index in skf.split(X, Y):  
  X_train, X_test = X[all_index], X[test_index]
  y_train, y_test = Y[all_index], Y[test_index]# -*- coding: utf-8 -*-

  skf2 = StratifiedKFold(n_splits=(numoffold-1),shuffle=True, random_state = None)
  skf2.get_n_splits(X_train, y_train)
  for train_index, val_index in skf2.split(X_train, y_train):  
    X_train2, X_val =   X_train[train_index], X_train[val_index]
    y_train2, y_val =  y_train[train_index], y_train[val_index]# -*- coding: utf-8 -*-
    break

  print(X_train2)
  print(X_val)
  print(X_test)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[ 1]
 [10]]
[[2]
 [9]]
[[ 1]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [10]]
[[2]
 [9]]
[[3]
 [7]]
[[ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 9]
 [10]]
[[2]
 [7]]
[[1]
 [8]]
[[ 2]
 [ 3]
 [ 4]
 [ 7]
 [ 8]
 [10]]
[[1]
 [9]]
[[5]
 [6]]
[[1]
 [2]
 [5]
 [7]
 [8]
 [9]]
[[3]
 [6]]
[[ 4]
 [10]]
