<a href="https://colab.research.google.com/github/oytungunes/PythonBasicCodes/blob/main/reversenumpyarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

example

sample input:
1 2 3 4 -8 -10

sample output:
[-10.  -8.   4.   3.   2.   1.]



In [7]:
import numpy 


def arrays(arr):
    # complete this function
    # use numpy.array
    arr2 = numpy.array(arr,float)
    arr3 = numpy.flip(arr2)
    return arr3

a = numpy.array([1,2,3,4,5])
print(a)
b = arrays(a)
print(b)



[1 2 3 4 5]
[5. 4. 3. 2. 1.]
